# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: Robby Stephenson <robby@periapsis.org>

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/linux-qt6.yml
      - /gitlab-templates/linux.yml
      - /gitlab-templates/freebsd-qt6.yml
      - /gitlab-templates/freebsd.yml
      - /gitlab-templates/flatpak.yml   
      - /gitlab-templates/craft-windows-x86-64.yml
      - /gitlab-templates/craft-windows-x86-64-qt6.yml
      - /gitlab-templates/yaml-lint.yml
